config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root 'crawls#index'

  resources :crawls, except: [:edit]
  post '/crawls' => 'crawls#create', as: :create_new_crawl
  get '/crawls/:id/products.csv' => 'crawls#products_csv'

  mount LetterOpenerWeb::Engine, at: '/letter_opener'

end

app/models/concerns/socializable.rb
module Socializable
  extend ActiveSupport::Concern

  included do
    validates :uid, :token, presence: true
    belongs_to :user
  end

  # For common class methods
  module ClassMethods
    def create_account!(auth, user)
      credentials = auth.credentials
      create!( uid: auth.uid, token: credentials.token, user: user )
    end
  end
end

app/models/crawl.rb
require 'nokogiri'
require 'open-uri'
require 'open_uri_redirections'

class Crawl < ActiveRecord::Base
  belongs_to :user
  has_many :products, dependent: :destroy

  validates :url, :user_id, presence: true

  after_create :start_crawling

  def self.to_csv
    attributes = %w{url crawl_time num_of_records_crawled user}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |crawl|
        csv << attributes.map { |attr| self.fetch_entry(crawl, attr) }
      end
    end
  end

  def start_crawling
    start_time = Time.now
    # allow redirection from http -> https and vice-versa
    doc = Nokogiri::HTML(open(url, allow_redirections: :all))
    product_links = get_product_links(doc)
    product_links.compact.uniq.each do |link|
      @link = link
      doc = Nokogiri::HTML(open(@link))
      extract_data_from_crawled_product_page(doc)
      create_crawled_product
    end
    t = (Time.now - start_time).to_i.abs
    update_attributes(crawl_time: t, num_of_records_crawled: products.count)
  end

  def extract_data_from_crawled_product_page(doc)
    fetch_price_and_emi_data(doc)
    fetch_name_and_brand(doc)
    fetch_color_and_image(doc)
  end

  def fetch_price_and_emi_data(doc)
    original_price_field  =  doc.search('.pdpCutPrice')
    @original_price       =  original_price_field.present? ? original_price_field.first.children.first.text.scan(/[0123456789]/).join()  : ''
    @current_price        =  doc.search('#productPrice').first.attributes['value'].value
    emi_field             =  doc.search('.emi-price')
    @emi_starts_at        =  emi_field.present? ? emi_field.first.children.text.scan(/[0123456789]/).join() : 'NA'
  end

  def fetch_name_and_brand(doc)
    @name                 =  doc.search('#productNamePDP').first.attributes['value'].value
    @brand                =  doc.search('#brandName').first.attributes['value'].value
  end

  def fetch_color_and_image(doc)
    catalog_id            =  doc.search('#catalogId').first.attributes['value'].value
    data_attrs_field      =  doc.search('#attributesJson').first.children.to_s
    if data_attrs_field.present?
      data_attrs          =  JSON.parse(data_attrs_field)
      product             =  data_attrs.select { |x| x["catalogId"] == catalog_id.to_i }.first
      @color              =  (product && product['name'] == 'Colour') ? product['value'] : ''
      @image_url          =  (product && product['thumbnail']) ? product['thumbnail'] : ''
    else
      @color              =  ""
      @image_url          =  doc.search('.cloudzoom').first.attributes['src'].value
    end

  end
  def get_product_links(doc)
    product_links = []
    doc.css("a").each do |x|
      link = x.attr('href')
      product_links << link if link && link.include?('https://www.snapdeal.com/product/')
    end
    return product_links
  end

  def create_crawled_product
    product                = self.products.where(product_url: @link).first_or_initialize
    product.name           = @name
    product.brand          = @brand
    product.original_price = @original_price
    product.current_price  = @current_price
    product.emi_starts_at  = @emi_starts_at
    product.image_url      = @image_url
    product.color          = @color
    product.save
  end

  def self.fetch_entry(crawl, attr)
    attr == 'user' ? crawl.send('user').email : crawl.send(attr)
  end
end

app/models/facebook_account.rb
class FacebookAccount < ActiveRecord::Base
  include Socializable
end

app/models/google_account.rb
class GoogleAccount < ActiveRecord::Base
  include Socializable
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :crawl

  def self.to_csv
    attributes = %w{name original_price current_price emi_starts_at image_url brand color product_url}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |product|
        csv << attributes.map do |attr|
          product.send(attr)
        end
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google]
  has_many :crawls
  has_one :facebook_account, dependent: :destroy
  has_one :google_account, dependent: :destroy

  def self.create_user!(info)
    create!(
      first_name: info.first_name, last_name: info.last_name,
      email: info.email, password: Devise.friendly_token[0, 20]
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/crawls_controller.rb
class CrawlsController < ApplicationController
  before_action :authenticate_user!

  def new
    @crawl = current_user.crawls.new
  end

  def create
    Crawl.create(crawl_params)
    redirect_to root_path
  end

  def index
    @crawls = current_user.crawls
    respond_to do |format|
      format.html
      format.csv { send_data @crawls.to_csv, filename: "crawls-#{Date.today}.csv" }
    end
  end

  def update
    @crawl = Crawl.find(params[:id])
    @crawl.start_crawling
    redirect_to crawl_path(@crawl)
  end

  def show
    @crawl = Crawl.find(params[:id])
    @products = @crawl.products
  end

  def products_csv
    @crawl = Crawl.find(params[:id])
    @products = @crawl.products
    send_data @products.to_csv, filename: "products-#{Date.today}.csv"
  end

  def destroy
    @crawl = Crawl.find(params[:id])
    @crawl.destroy
    redirect_to root_path
  end

  private

  def crawl_params
    params.require(:crawl).permit(:url).merge(user_id: current_user.id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  # For Signin with facebook and google
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    before_action :find_or_create_user, only: [:google]

    def google
      GoogleAccount.create_account!(@auth, @user) unless @user.google_account
      sign_in_user('Google')
    end

    private

    def find_or_create_user
      @auth = env['omniauth.auth']
      info = @auth.info
      @user = User.where(email: info.email).first || User.create_user!(info)
    end

    def sign_in_user(login_provider)
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: login_provider)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def color(color)
    color.present? ? color.capitalize : 'NA'
  end

  def amount(amount)
    amount.present? ? "₹ #{amount}" : 'NA'
  end

  def truncated_url(url)
    url.split("").each_with_object("") do
      |x,ob| break ob unless (ob.length + " ".length + x.length <= 80);ob << ("" + x)
    end.strip
  end
end

app/views/crawls/index.html.haml
.row
  %p
  %h1 Total Crawled Web Pages: #{@crawls.count}
  %p To begin a new crawl, hit crawl.
  %p  
  .col-md-12
    %input#searchBox{ placeholder: "Search..", type: "text" }
    .panel.panel-default.panel-table
      .panel-heading
        .row
          .col.col-xs-6
            %h3.panel-title Crawls List
          .col.col-xs-6.text-right
            = link_to new_crawl_path do
              %button.btn.btn-sm.btn-primary.btn-create{:type => "button"} New Crawl
      .panel-body
        %table.tablesorter.table.table-striped.table-bordered.table-list
          %thead
            %tr
              %th.col-md-7 Crawled URL
              %th.col-md-1 Records
              %th.col-md-1 Time Taken
              %th.sorter-false.col-md-3
                %em.fa.fa-cog
          %tbody
            - @crawls.each do |crawl|
              %tr.results.data-href{'data-href'=> crawl_path(crawl)}
                %td
                  = link_to crawl.url do
                    = truncated_url(crawl.url)
                %td= crawl.num_of_records_crawled
                %td= "#{crawl.crawl_time} seconds"
                %td.sorter-false
                  = link_to crawl_path(crawl), method: :patch do
                    .btn.btn-default
                      %em.fa.fa-refresh
                      ReCrawl
                  = link_to crawl_path(crawl), method: :delete do
                    .btn.btn-danger
                      %em.fa.fa-trash
                      Delete
.text-right
  = link_to '/crawls.csv' do
    %button.btn.btn-sm.btn-primary.btn-create{:type => "button"} Download CSV File
:javascript
  crawler.table.init();

app/views/crawls/new.html.haml
.mainbox.col-md-6.col-md-offset-3.col-sm-8.col-sm-offset-2{style: "margin-top:80px;"}
  .panel.panel-info
    .panel-heading
      .panel-title Begin A new Crawl
    .panel-body{:style => "padding-top:30px"}
      = form_for @crawl, html: { class: 'form-horizontal' } do |f|
        .input-group{:style => "margin-bottom: 25px"}
          %span.input-group-addon
            %i.glyphicon.glyphicon-circle-arrow-right
          = f.text_field :url, autofocus: true, class: 'form-control', placeholder: "Enter URL here", required: "", type: "url"
        .form-group{:style => "margin-top:10px"}
          .col-sm-12.controls
            %button#btn-login.btn.btn-success.btn-crawl{type: 'submit'} Start Crawling
.loader{style: "display:none"}
  = image_tag 'gears', id: 'loader'

app/views/crawls/show.html.haml
.row
  .text-right
    = link_to "/crawls/#{@crawl.id}/products.csv" do
      %button.btn.btn-sm.btn-primary.btn-create{:type => "button"} Download CSV File
    = link_to crawl_path(@crawl), method: :patch do
      .btn.btn-default
        %em.fa.fa-refresh
        ReCrawl
  %h1 Total Fetched Products: #{@products.count}
  %p  
  .col-md-12
    %input#searchBox{ placeholder: "Search..", type: "text" }
    .panel.panel-default.panel-table
      .panel-heading
        .row
          .col.col-xs-6
            %h3.panel-title Products List
      .panel-body
        %table.tablesorter.table.table-striped.table-bordered.table-list
          %thead
            %tr
              %th.col-md-4 Name
              %th.col-md-2 Original Price
              %th.col-md-2 Current Price
              %th.col-md-1 Lowest EMI
              %th.col-md-1 Image
              %th.col-md-1 Brand
              %th.col-md-1 Color
          %tbody
            - @products.each do |product|
              %tr.results.data-href{'data-href' => product.product_url}
                %td= product.name
                %td= amount(product.original_price)
                %td= amount(product.current_price)
                %td= amount(product.emi_starts_at)
                %td
                  = image_tag(product.image_url, height: '45', width: '45')
                %td= product.brand.try(:titleize)
                %td= color(product.color)
:javascript
  crawler.table.init();

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Snapdeal Crawler
    = stylesheet_link_tag    'application'
    = stylesheet_link_tag    'style'
    = javascript_include_tag 'application'
    = javascript_include_tag 'jquery.tablesorter.min'
    = csrf_meta_tags
    %meta{:content => "eBqfMf_lPyjXpAjVWQnFNHshGoDN8YbdaXXWINjlOuE", :name => "google-site-verification"}/
  %body
    %nav.navbar.navbar-default.navbar-fixed-top.navbar-inverse{ role: 'navigation' }
      .container
        .navbar-header
          = link_to 'Snapdeal Crawler', root_path, class: 'navbar-brand'
        .collapse.navbar-collapse
          - if current_user
            %ul.nav.navbar-nav.navbar-right
              %li.dropdown
                %a.dropdown-toggle{ role: 'button', href: '#', data: {toggle: 'dropdown'}, aria: {haspopup: 'true', expanded: 'false'} }
                  = "Welcome #{current_user.email}!"
                  %span.caret
                %ul.dropdown-menu
                  %li
                    =link_to 'Sign out', destroy_user_session_path, method: :delete
    .container.admin-page-tables
      = yield
:javascript
  window.crawler.header.init();